title: Local storage (lokale opslag) gebruiken
hero_image: images/banner.png
description: Local storage gebruiken
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Local storage (lokale opslag) gebruiken
